#!/bin/bash --login
source ~/.bashrc

__DIR="/home/chenhao.xue/chipyard"
PATH=$__DIR/software/firemarshal:$PATH
# line auto-generated by ./build-setup.sh
conda activate /home/chenhao.xue/chipyard/.conda-env
source /home/chenhao.xue/chipyard/scripts/fix-open-files.sh

BOOM_CFG_IDX=$(python gen_boom_config.py)
echo $BOOM_CFG_IDX

